<?php

declare(strict_types=1);

namespace OCA\FitTracker\Service;

/**
 * Authoritative FIT `sport` / `sub_sport` enum tables, transcribed from Garmin's
 * official FIT SDK Profile.xlsx (Types sheet — https://github.com/garmin/fit-sdk-tools).
 *
 * The phpFITFileAnalysis vendor library only ships sport 0-19 (+254) and
 * sub_sport 0-28 (+254); anything outside that range decodes to 'unknown'
 * through its enumData(), which is what caused unrelated sports (e.g. sailing,
 * id 32) to fall through to the old GPS-present-so-must-be-running heuristic.
 * FitParserService reads session['sport']/['sub_sport'] as raw ints and looks
 * them up here directly instead of relying on that decoder.
 */
class FitSportProfile {

    public const SPORTS = [
        0 => 'generic',
        1 => 'running',
        2 => 'cycling',
        3 => 'transition',
        4 => 'fitness_equipment',
        5 => 'swimming',
        6 => 'basketball',
        7 => 'soccer',
        8 => 'tennis',
        9 => 'american_football',
        10 => 'training',
        11 => 'walking',
        12 => 'cross_country_skiing',
        13 => 'alpine_skiing',
        14 => 'snowboarding',
        15 => 'rowing',
        16 => 'mountaineering',
        17 => 'hiking',
        18 => 'multisport',
        19 => 'paddling',
        20 => 'flying',
        21 => 'e_biking',
        22 => 'motorcycling',
        23 => 'boating',
        24 => 'driving',
        25 => 'golf',
        26 => 'hang_gliding',
        27 => 'horseback_riding',
        28 => 'hunting',
        29 => 'fishing',
        30 => 'inline_skating',
        31 => 'rock_climbing',
        32 => 'sailing',
        33 => 'ice_skating',
        34 => 'sky_diving',
        35 => 'snowshoeing',
        36 => 'snowmobiling',
        37 => 'stand_up_paddleboarding',
        38 => 'surfing',
        39 => 'wakeboarding',
        40 => 'water_skiing',
        41 => 'kayaking',
        42 => 'rafting',
        43 => 'windsurfing',
        44 => 'kitesurfing',
        45 => 'tactical',
        46 => 'jumpmaster',
        47 => 'boxing',
        48 => 'floor_climbing',
        49 => 'baseball',
        53 => 'diving',
        56 => 'shooting',
        58 => 'winter_sport',
        59 => 'grinding',
        62 => 'hiit',
        63 => 'video_gaming',
        64 => 'racket',
        65 => 'wheelchair_push_walk',
        66 => 'wheelchair_push_run',
        67 => 'meditation',
        68 => 'para_sport',
        69 => 'disc_golf',
        70 => 'team_sport',
        71 => 'cricket',
        72 => 'rugby',
        73 => 'hockey',
        74 => 'lacrosse',
        75 => 'volleyball',
        76 => 'water_tubing',
        77 => 'wakesurfing',
        78 => 'water_sport',
        79 => 'archery',
        80 => 'mixed_martial_arts',
        81 => 'motor_sports',
        82 => 'snorkeling',
        83 => 'dance',
        84 => 'jump_rope',
        85 => 'pool_apnea',
        86 => 'mobility',
        87 => 'geocaching',
        88 => 'canoeing',
        254 => 'all',
    ];

    public const SUB_SPORTS = [
        0 => 'generic',
        1 => 'treadmill',
        2 => 'street',
        3 => 'trail',
        4 => 'track',
        5 => 'spin',
        6 => 'indoor_cycling',
        7 => 'road',
        8 => 'mountain',
        9 => 'downhill',
        10 => 'recumbent',
        11 => 'cyclocross',
        12 => 'hand_cycling',
        13 => 'track_cycling',
        14 => 'indoor_rowing',
        15 => 'elliptical',
        16 => 'stair_climbing',
        17 => 'lap_swimming',
        18 => 'open_water',
        19 => 'flexibility_training',
        20 => 'strength_training',
        21 => 'warm_up',
        22 => 'match',
        23 => 'exercise',
        24 => 'challenge',
        25 => 'indoor_skiing',
        26 => 'cardio_training',
        27 => 'indoor_walking',
        28 => 'e_bike_fitness',
        29 => 'bmx',
        30 => 'casual_walking',
        31 => 'speed_walking',
        32 => 'bike_to_run_transition',
        33 => 'run_to_bike_transition',
        34 => 'swim_to_bike_transition',
        35 => 'atv',
        36 => 'motocross',
        37 => 'backcountry',
        38 => 'resort',
        39 => 'rc_drone',
        40 => 'wingsuit',
        41 => 'whitewater',
        42 => 'skate_skiing',
        43 => 'yoga',
        44 => 'pilates',
        45 => 'indoor_running',
        46 => 'gravel_cycling',
        47 => 'e_bike_mountain',
        48 => 'commuting',
        49 => 'mixed_surface',
        50 => 'navigate',
        51 => 'track_me',
        52 => 'map',
        53 => 'single_gas_diving',
        54 => 'multi_gas_diving',
        55 => 'gauge_diving',
        56 => 'apnea_diving',
        57 => 'apnea_hunting',
        58 => 'virtual_activity',
        59 => 'obstacle',
        62 => 'breathing',
        63 => 'ccr_diving',
        65 => 'sail_race',
        66 => 'expedition',
        67 => 'ultra',
        68 => 'indoor_climbing',
        69 => 'bouldering',
        70 => 'hiit',
        71 => 'indoor_grinding',
        72 => 'hunting_with_dogs',
        73 => 'amrap',
        74 => 'emom',
        75 => 'tabata',
        77 => 'esport',
        78 => 'triathlon',
        79 => 'duathlon',
        80 => 'brick',
        81 => 'swim_run',
        82 => 'adventure_race',
        83 => 'trucker_workout',
        84 => 'pickleball',
        85 => 'padel',
        86 => 'indoor_wheelchair_walk',
        87 => 'indoor_wheelchair_run',
        88 => 'indoor_hand_cycling',
        90 => 'field',
        91 => 'ice',
        92 => 'ultimate',
        93 => 'platform',
        94 => 'squash',
        95 => 'badminton',
        96 => 'racquetball',
        97 => 'table_tennis',
        98 => 'overland',
        99 => 'trolling_motor',
        110 => 'fly_canopy',
        111 => 'fly_paraglide',
        112 => 'fly_paramotor',
        113 => 'fly_pressurized',
        114 => 'fly_navigate',
        115 => 'fly_timer',
        116 => 'fly_altimeter',
        117 => 'fly_wx',
        118 => 'fly_vfr',
        119 => 'fly_ifr',
        121 => 'dynamic_apnea',
        123 => 'enduro',
        124 => 'rucking',
        125 => 'rally',
        126 => 'pool_triathlon',
        127 => 'e_bike_enduro',
        254 => 'all',
    ];
}
